-- One-shot setup for a NEW Supabase project (e.g. bgbgiazicjfpninnizjn).
-- Paste this entire file in: Dashboard → SQL → New query → Run.
-- Do NOT paste file paths — only this SQL.

-- 1) Leads
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  full_name text,
  phone text,
  email text,
  destination text,
  travel_dates text,
  number_of_travelers text,
  budget text,
  message text,
  source text default 'Website',
  status text default 'New',
  notes text,
  follow_up_date date,
  assigned_agent text,
  deal_value numeric(12, 2) not null default 0,
  trip_type text,
  priority text default 'Normal',
  package_interest text,
  client_id bigint,
  created_at timestamptz not null default now()
);

-- 2) Clients
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  first_name text not null default '',
  last_name text not null default '',
  email text,
  phone text,
  nationality text,
  date_of_birth date,
  passport_number text,
  date_of_issue date,
  date_of_expiry date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.leads
  drop constraint if exists leads_client_id_fkey;

alter table public.leads
  add constraint leads_client_id_fkey
  foreign key (client_id) references public.clients(id) on delete set null;

-- 3) Lead activities
create table if not exists public.lead_activities (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  type text not null,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by uuid
);

create index if not exists idx_leads_created_at on public.leads(created_at desc);
create index if not exists idx_leads_client_id on public.leads(client_id);
create index if not exists idx_clients_email on public.clients(lower(email));
create index if not exists idx_activities_lead_id_created_at on public.lead_activities(lead_id, created_at desc);

-- 4) Corporate / group partners
create table if not exists public.corporate_groups (
  id bigint generated by default as identity primary key,
  company_name text not null default '',
  industry text,
  status text not null default 'Active',
  contact_person text,
  contact_email text,
  contact_phone text,
  vat_number text,
  website text,
  address text,
  city text,
  country text default 'Cyprus',
  typical_group_size text,
  payment_terms text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_corporate_groups_company on public.corporate_groups(lower(company_name));
create index if not exists idx_corporate_groups_status on public.corporate_groups(status);

-- 5) Client financial records (invoices, receipts, margin)
create table if not exists public.client_financial_records (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  lead_id bigint references public.leads(id) on delete set null,
  record_type text not null default 'invoice',
  reference_no text,
  title text not null default '',
  sell_price numeric(12, 2) not null default 0,
  net_price numeric(12, 2) not null default 0,
  margin numeric(12, 2) generated always as (sell_price - net_price) stored,
  amount_received numeric(12, 2) not null default 0,
  currency text not null default 'EUR',
  payment_status text not null default 'pending',
  payment_method text,
  invoice_date date,
  due_date date,
  paid_date date,
  supplier_name text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_client_financials_client on public.client_financial_records(client_id);
create index if not exists idx_client_financials_lead on public.client_financial_records(lead_id);

-- 6) Team hub (shared tasks & news)
create table if not exists public.team_tasks (
  id bigint generated by default as identity primary key,
  title text not null default '',
  description text,
  status text not null default 'todo',
  priority text not null default 'normal',
  assigned_to text,
  created_by_id uuid,
  created_by_name text not null default 'Agent',
  due_date date,
  task_type text not null default 'general',
  client_id bigint references public.clients(id) on delete set null,
  lead_id bigint references public.leads(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_updates (
  id bigint generated by default as identity primary key,
  title text not null default '',
  body text not null default '',
  category text not null default 'update',
  pinned boolean not null default false,
  image_url text,
  link_url text,
  created_by_id uuid,
  created_by_name text not null default 'Agent',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_task_comments (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.team_tasks(id) on delete cascade,
  body text not null default '',
  created_by_id uuid,
  created_by_name text not null default 'Agent',
  created_at timestamptz not null default now()
);

create index if not exists idx_team_tasks_status on public.team_tasks(status);
create index if not exists idx_team_tasks_due on public.team_tasks(due_date);
create index if not exists idx_team_tasks_client on public.team_tasks(client_id);
create index if not exists idx_team_tasks_type on public.team_tasks(task_type);
create index if not exists idx_team_task_comments_task on public.team_task_comments(task_id, created_at);

alter table public.leads enable row level security;
alter table public.clients enable row level security;
alter table public.lead_activities enable row level security;
alter table public.corporate_groups enable row level security;
alter table public.client_financial_records enable row level security;
alter table public.team_tasks enable row level security;
alter table public.team_updates enable row level security;
alter table public.team_task_comments enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'leads' and policyname = 'Authenticated can read leads') then
    create policy "Authenticated can read leads" on public.leads for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'leads' and policyname = 'Authenticated can insert leads') then
    create policy "Authenticated can insert leads" on public.leads for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'leads' and policyname = 'Authenticated can update leads') then
    create policy "Authenticated can update leads" on public.leads for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'leads' and policyname = 'Authenticated can delete leads') then
    create policy "Authenticated can delete leads" on public.leads for delete to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'clients' and policyname = 'Authenticated can read clients') then
    create policy "Authenticated can read clients" on public.clients for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'clients' and policyname = 'Authenticated can insert clients') then
    create policy "Authenticated can insert clients" on public.clients for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'clients' and policyname = 'Authenticated can update clients') then
    create policy "Authenticated can update clients" on public.clients for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'clients' and policyname = 'Authenticated can delete clients') then
    create policy "Authenticated can delete clients" on public.clients for delete to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'lead_activities' and policyname = 'Authenticated can read lead activities') then
    create policy "Authenticated can read lead activities" on public.lead_activities for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'lead_activities' and policyname = 'Authenticated can insert lead activities') then
    create policy "Authenticated can insert lead activities" on public.lead_activities for insert to authenticated with check (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'corporate_groups' and policyname = 'Authenticated can read corporate_groups') then
    create policy "Authenticated can read corporate_groups" on public.corporate_groups for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'corporate_groups' and policyname = 'Authenticated can insert corporate_groups') then
    create policy "Authenticated can insert corporate_groups" on public.corporate_groups for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'corporate_groups' and policyname = 'Authenticated can update corporate_groups') then
    create policy "Authenticated can update corporate_groups" on public.corporate_groups for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'corporate_groups' and policyname = 'Authenticated can delete corporate_groups') then
    create policy "Authenticated can delete corporate_groups" on public.corporate_groups for delete to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'client_financial_records' and policyname = 'Authenticated can read client_financial_records') then
    create policy "Authenticated can read client_financial_records" on public.client_financial_records for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'client_financial_records' and policyname = 'Authenticated can insert client_financial_records') then
    create policy "Authenticated can insert client_financial_records" on public.client_financial_records for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'client_financial_records' and policyname = 'Authenticated can update client_financial_records') then
    create policy "Authenticated can update client_financial_records" on public.client_financial_records for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'client_financial_records' and policyname = 'Authenticated can delete client_financial_records') then
    create policy "Authenticated can delete client_financial_records" on public.client_financial_records for delete to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'team_tasks' and policyname = 'Authenticated can read team_tasks') then
    create policy "Authenticated can read team_tasks" on public.team_tasks for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_tasks' and policyname = 'Authenticated can insert team_tasks') then
    create policy "Authenticated can insert team_tasks" on public.team_tasks for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_tasks' and policyname = 'Authenticated can update team_tasks') then
    create policy "Authenticated can update team_tasks" on public.team_tasks for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_tasks' and policyname = 'Authenticated can delete team_tasks') then
    create policy "Authenticated can delete team_tasks" on public.team_tasks for delete to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_updates' and policyname = 'Authenticated can read team_updates') then
    create policy "Authenticated can read team_updates" on public.team_updates for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_updates' and policyname = 'Authenticated can insert team_updates') then
    create policy "Authenticated can insert team_updates" on public.team_updates for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_updates' and policyname = 'Authenticated can update team_updates') then
    create policy "Authenticated can update team_updates" on public.team_updates for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_updates' and policyname = 'Authenticated can delete team_updates') then
    create policy "Authenticated can delete team_updates" on public.team_updates for delete to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_task_comments' and policyname = 'Authenticated can read team_task_comments') then
    create policy "Authenticated can read team_task_comments" on public.team_task_comments for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_task_comments' and policyname = 'Authenticated can insert team_task_comments') then
    create policy "Authenticated can insert team_task_comments" on public.team_task_comments for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_task_comments' and policyname = 'Authenticated can delete team_task_comments') then
    create policy "Authenticated can delete team_task_comments" on public.team_task_comments for delete to authenticated using (true);
  end if;
end $$;

grant select, insert, update, delete on table public.corporate_groups to authenticated;
grant select on table public.corporate_groups to anon;
grant select, insert, update, delete on table public.client_financial_records to authenticated;
grant select, insert, update, delete on table public.team_tasks to authenticated;
grant select, insert, update, delete on table public.team_updates to authenticated;
grant select, insert, delete on table public.team_task_comments to authenticated;

notify pgrst, 'reload schema';
