-- Team tasks & news hub. Safe to re-run. Paste in Supabase SQL editor.
-- (Same as supabase/migrations/20260526_team_hub.sql)

create table if not exists public.team_tasks (
  id bigint generated by default as identity primary key,
  title text not null default '',
  description text,
  status text not null default 'todo',
  priority text not null default 'normal',
  assigned_to text,
  created_by_id uuid,
  created_by_name text not null default 'Agent',
  due_date date,
  task_type text not null default 'general',
  client_id bigint references public.clients(id) on delete set null,
  lead_id bigint references public.leads(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_updates (
  id bigint generated by default as identity primary key,
  title text not null default '',
  body text not null default '',
  category text not null default 'update',
  pinned boolean not null default false,
  created_by_id uuid,
  created_by_name text not null default 'Agent',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_task_comments (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.team_tasks(id) on delete cascade,
  body text not null default '',
  created_by_id uuid,
  created_by_name text not null default 'Agent',
  created_at timestamptz not null default now()
);

-- If team_tasks already existed (older script), add missing columns before indexes
alter table public.team_tasks
  add column if not exists task_type text not null default 'general';

alter table public.team_tasks
  add column if not exists due_date date;

alter table public.team_tasks
  add column if not exists client_id bigint references public.clients(id) on delete set null;

alter table public.team_tasks
  add column if not exists lead_id bigint references public.leads(id) on delete set null;

create index if not exists idx_team_tasks_status on public.team_tasks(status);
create index if not exists idx_team_tasks_assigned on public.team_tasks(assigned_to);
create index if not exists idx_team_tasks_due on public.team_tasks(due_date);
create index if not exists idx_team_tasks_client on public.team_tasks(client_id);
create index if not exists idx_team_tasks_type on public.team_tasks(task_type);
create index if not exists idx_team_updates_pinned on public.team_updates(pinned desc, created_at desc);
create index if not exists idx_team_task_comments_task on public.team_task_comments(task_id, created_at);

alter table public.team_tasks enable row level security;
alter table public.team_updates enable row level security;
alter table public.team_task_comments enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'team_tasks' and policyname = 'Authenticated can read team_tasks') then
    create policy "Authenticated can read team_tasks" on public.team_tasks for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_tasks' and policyname = 'Authenticated can insert team_tasks') then
    create policy "Authenticated can insert team_tasks" on public.team_tasks for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_tasks' and policyname = 'Authenticated can update team_tasks') then
    create policy "Authenticated can update team_tasks" on public.team_tasks for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_tasks' and policyname = 'Authenticated can delete team_tasks') then
    create policy "Authenticated can delete team_tasks" on public.team_tasks for delete to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_updates' and policyname = 'Authenticated can read team_updates') then
    create policy "Authenticated can read team_updates" on public.team_updates for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_updates' and policyname = 'Authenticated can insert team_updates') then
    create policy "Authenticated can insert team_updates" on public.team_updates for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_updates' and policyname = 'Authenticated can update team_updates') then
    create policy "Authenticated can update team_updates" on public.team_updates for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_updates' and policyname = 'Authenticated can delete team_updates') then
    create policy "Authenticated can delete team_updates" on public.team_updates for delete to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_task_comments' and policyname = 'Authenticated can read team_task_comments') then
    create policy "Authenticated can read team_task_comments" on public.team_task_comments for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_task_comments' and policyname = 'Authenticated can insert team_task_comments') then
    create policy "Authenticated can insert team_task_comments" on public.team_task_comments for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'team_task_comments' and policyname = 'Authenticated can delete team_task_comments') then
    create policy "Authenticated can delete team_task_comments" on public.team_task_comments for delete to authenticated using (true);
  end if;
end $$;

grant select, insert, update, delete on table public.team_tasks to authenticated;
grant select, insert, update, delete on table public.team_updates to authenticated;
grant select, insert, delete on table public.team_task_comments to authenticated;

notify pgrst, 'reload schema';
