-- Corporate services contacts directory. Safe to re-run.

create table if not exists public.corporate_service_contacts (
  id bigint generated by default as identity primary key,
  organization text not null default '',
  contact_name text,
  job_title text,
  category text not null default 'Other',
  status text not null default 'Active',
  email text,
  phone text,
  mobile text,
  city text,
  country text default 'Cyprus',
  website text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_corp_svc_contacts_org on public.corporate_service_contacts(lower(organization));
create index if not exists idx_corp_svc_contacts_category on public.corporate_service_contacts(category);

alter table public.corporate_service_contacts enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'corporate_service_contacts'
      and policyname = 'Authenticated can read corporate_service_contacts'
  ) then
    create policy "Authenticated can read corporate_service_contacts"
      on public.corporate_service_contacts for select to authenticated using (true);
  end if;
  if not exists (
    select 1 from pg_policies where tablename = 'corporate_service_contacts'
      and policyname = 'Authenticated can insert corporate_service_contacts'
  ) then
    create policy "Authenticated can insert corporate_service_contacts"
      on public.corporate_service_contacts for insert to authenticated with check (true);
  end if;
  if not exists (
    select 1 from pg_policies where tablename = 'corporate_service_contacts'
      and policyname = 'Authenticated can update corporate_service_contacts'
  ) then
    create policy "Authenticated can update corporate_service_contacts"
      on public.corporate_service_contacts for update to authenticated using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies where tablename = 'corporate_service_contacts'
      and policyname = 'Authenticated can delete corporate_service_contacts'
  ) then
    create policy "Authenticated can delete corporate_service_contacts"
      on public.corporate_service_contacts for delete to authenticated using (true);
  end if;
end $$;

grant select, insert, update, delete on table public.corporate_service_contacts to authenticated;

notify pgrst, 'reload schema';
