-- Client accounting table (invoices, receipts, sell/net/margin). Safe to re-run.
-- Paste in: Supabase Dashboard → SQL → Run

create table if not exists public.client_financial_records (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  lead_id bigint references public.leads(id) on delete set null,
  record_type text not null default 'invoice',
  reference_no text,
  title text not null default '',
  sell_price numeric(12, 2) not null default 0,
  net_price numeric(12, 2) not null default 0,
  margin numeric(12, 2) generated always as (sell_price - net_price) stored,
  amount_received numeric(12, 2) not null default 0,
  currency text not null default 'EUR',
  payment_status text not null default 'pending',
  payment_method text,
  invoice_date date,
  due_date date,
  paid_date date,
  supplier_name text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_client_financials_client on public.client_financial_records(client_id);
create index if not exists idx_client_financials_lead on public.client_financial_records(lead_id);

alter table public.client_financial_records enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where tablename = 'client_financial_records' and policyname = 'Authenticated can read client_financial_records'
  ) then
    create policy "Authenticated can read client_financial_records"
      on public.client_financial_records for select to authenticated using (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where tablename = 'client_financial_records' and policyname = 'Authenticated can insert client_financial_records'
  ) then
    create policy "Authenticated can insert client_financial_records"
      on public.client_financial_records for insert to authenticated with check (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where tablename = 'client_financial_records' and policyname = 'Authenticated can update client_financial_records'
  ) then
    create policy "Authenticated can update client_financial_records"
      on public.client_financial_records for update to authenticated using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where tablename = 'client_financial_records' and policyname = 'Authenticated can delete client_financial_records'
  ) then
    create policy "Authenticated can delete client_financial_records"
      on public.client_financial_records for delete to authenticated using (true);
  end if;
end $$;

grant select, insert, update, delete on table public.client_financial_records to authenticated;

notify pgrst, 'reload schema';
