-- Travel package quote calculator. Safe to re-run in Supabase SQL editor.

create table if not exists public.package_quotes (
  id bigint generated by default as identity primary key,
  title text not null default 'Untitled package',
  client_name text,
  destination text,
  trip_type text,
  pax integer default 2,
  currency text not null default 'EUR',
  target_margin_percent numeric default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.package_quote_lines (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.package_quotes(id) on delete cascade,
  sort_order integer not null default 0,
  service_name text not null default '',
  category text not null default 'Other',
  supplier text,
  quantity numeric not null default 1,
  net_price numeric not null default 0,
  sell_price numeric not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_package_quote_lines_quote on public.package_quote_lines(quote_id, sort_order);

alter table public.package_quotes enable row level security;
alter table public.package_quote_lines enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'package_quotes' and policyname = 'Authenticated can read package_quotes'
  ) then
    create policy "Authenticated can read package_quotes"
      on public.package_quotes for select to authenticated using (true);
  end if;
  if not exists (
    select 1 from pg_policies where tablename = 'package_quotes' and policyname = 'Authenticated can insert package_quotes'
  ) then
    create policy "Authenticated can insert package_quotes"
      on public.package_quotes for insert to authenticated with check (true);
  end if;
  if not exists (
    select 1 from pg_policies where tablename = 'package_quotes' and policyname = 'Authenticated can update package_quotes'
  ) then
    create policy "Authenticated can update package_quotes"
      on public.package_quotes for update to authenticated using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies where tablename = 'package_quotes' and policyname = 'Authenticated can delete package_quotes'
  ) then
    create policy "Authenticated can delete package_quotes"
      on public.package_quotes for delete to authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'package_quote_lines' and policyname = 'Authenticated can read package_quote_lines'
  ) then
    create policy "Authenticated can read package_quote_lines"
      on public.package_quote_lines for select to authenticated using (true);
  end if;
  if not exists (
    select 1 from pg_policies where tablename = 'package_quote_lines' and policyname = 'Authenticated can insert package_quote_lines'
  ) then
    create policy "Authenticated can insert package_quote_lines"
      on public.package_quote_lines for insert to authenticated with check (true);
  end if;
  if not exists (
    select 1 from pg_policies where tablename = 'package_quote_lines' and policyname = 'Authenticated can update package_quote_lines'
  ) then
    create policy "Authenticated can update package_quote_lines"
      on public.package_quote_lines for update to authenticated using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies where tablename = 'package_quote_lines' and policyname = 'Authenticated can delete package_quote_lines'
  ) then
    create policy "Authenticated can delete package_quote_lines"
      on public.package_quote_lines for delete to authenticated using (true);
  end if;
end $$;

grant select, insert, update, delete on table public.package_quotes to authenticated;
grant select, insert, update, delete on table public.package_quote_lines to authenticated;

notify pgrst, 'reload schema';
