-- Gift Vouchers — full setup (safe to re-run). Paste in Supabase SQL Editor.

create table if not exists public.voucher_receivers (
  id bigint generated by default as identity primary key,
  full_name text not null default '',
  phone text,
  email text,
  nationality text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gift_vouchers (
  id bigint generated by default as identity primary key,
  voucher_code text not null unique,
  voucher_title text not null default '',
  voucher_type text not null default 'custom',
  receiver_id bigint references public.voucher_receivers(id) on delete set null,
  total_amount numeric(12, 2) not null default 0,
  currency text not null default 'EUR',
  status text not null default 'draft',
  expiry_date date,
  gift_message text,
  template_key text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.voucher_senders (
  id bigint generated by default as identity primary key,
  voucher_id bigint not null references public.gift_vouchers(id) on delete cascade,
  full_name text not null default '',
  phone text,
  email text,
  contribution_amount numeric(12, 2) not null default 0,
  payment_status text not null default 'pending',
  payment_method text,
  payment_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.voucher_payments (
  id bigint generated by default as identity primary key,
  voucher_id bigint not null references public.gift_vouchers(id) on delete cascade,
  sender_id bigint references public.voucher_senders(id) on delete set null,
  amount numeric(12, 2) not null default 0,
  payment_method text,
  payment_status text not null default 'paid',
  payment_date timestamptz not null default now(),
  notes text,
  created_by_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.voucher_activities (
  id bigint generated by default as identity primary key,
  voucher_id bigint not null references public.gift_vouchers(id) on delete cascade,
  activity_type text not null default 'note',
  description text not null default '',
  metadata jsonb,
  created_by_name text,
  created_at timestamptz not null default now()
);

create index if not exists idx_gift_vouchers_code on public.gift_vouchers(lower(voucher_code));
create index if not exists idx_gift_vouchers_status on public.gift_vouchers(status);
create index if not exists idx_gift_vouchers_receiver on public.gift_vouchers(receiver_id);
create index if not exists idx_gift_vouchers_expiry on public.gift_vouchers(expiry_date);
create index if not exists idx_voucher_receivers_name on public.voucher_receivers(lower(full_name));
create index if not exists idx_voucher_receivers_phone on public.voucher_receivers(phone);
create index if not exists idx_voucher_receivers_email on public.voucher_receivers(lower(email));

alter table public.voucher_receivers
  add column if not exists client_id bigint references public.clients(id) on delete set null;

create index if not exists idx_voucher_receivers_client on public.voucher_receivers(client_id);

create index if not exists idx_voucher_senders_voucher on public.voucher_senders(voucher_id);
create index if not exists idx_voucher_senders_name on public.voucher_senders(lower(full_name));
create index if not exists idx_voucher_payments_voucher on public.voucher_payments(voucher_id);

alter table public.voucher_receivers enable row level security;
alter table public.gift_vouchers enable row level security;
alter table public.voucher_senders enable row level security;
alter table public.voucher_payments enable row level security;
alter table public.voucher_activities enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can read voucher_receivers') then
    create policy "Authenticated can read voucher_receivers" on public.voucher_receivers for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can insert voucher_receivers') then
    create policy "Authenticated can insert voucher_receivers" on public.voucher_receivers for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can update voucher_receivers') then
    create policy "Authenticated can update voucher_receivers" on public.voucher_receivers for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can delete voucher_receivers') then
    create policy "Authenticated can delete voucher_receivers" on public.voucher_receivers for delete to authenticated using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can read gift_vouchers') then
    create policy "Authenticated can read gift_vouchers" on public.gift_vouchers for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can insert gift_vouchers') then
    create policy "Authenticated can insert gift_vouchers" on public.gift_vouchers for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can update gift_vouchers') then
    create policy "Authenticated can update gift_vouchers" on public.gift_vouchers for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can delete gift_vouchers') then
    create policy "Authenticated can delete gift_vouchers" on public.gift_vouchers for delete to authenticated using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can read voucher_senders') then
    create policy "Authenticated can read voucher_senders" on public.voucher_senders for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can insert voucher_senders') then
    create policy "Authenticated can insert voucher_senders" on public.voucher_senders for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can update voucher_senders') then
    create policy "Authenticated can update voucher_senders" on public.voucher_senders for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can delete voucher_senders') then
    create policy "Authenticated can delete voucher_senders" on public.voucher_senders for delete to authenticated using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can read voucher_payments') then
    create policy "Authenticated can read voucher_payments" on public.voucher_payments for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can insert voucher_payments') then
    create policy "Authenticated can insert voucher_payments" on public.voucher_payments for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can update voucher_payments') then
    create policy "Authenticated can update voucher_payments" on public.voucher_payments for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can delete voucher_payments') then
    create policy "Authenticated can delete voucher_payments" on public.voucher_payments for delete to authenticated using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can read voucher_activities') then
    create policy "Authenticated can read voucher_activities" on public.voucher_activities for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated can insert voucher_activities') then
    create policy "Authenticated can insert voucher_activities" on public.voucher_activities for insert to authenticated with check (true);
  end if;
end $$;

grant select, insert, update, delete on table public.voucher_receivers to authenticated;
grant select, insert, update, delete on table public.gift_vouchers to authenticated;
grant select, insert, update, delete on table public.voucher_senders to authenticated;
grant select, insert, update, delete on table public.voucher_payments to authenticated;
grant select, insert, update, delete on table public.voucher_activities to authenticated;

notify pgrst, 'reload schema';
