-- Group bookings (cruise, school, corporate, incentive) and passenger rosters

create table if not exists public.travel_groups (
  id bigint generated by default as identity primary key,
  group_name text not null default '',
  group_type text not null default 'group_booking',
  departure_date date,
  return_date date,
  destination text,
  supplier text,
  status text not null default 'Planning',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_travel_groups_departure on public.travel_groups(departure_date);
create index if not exists idx_travel_groups_type on public.travel_groups(group_type);
create index if not exists idx_travel_groups_status on public.travel_groups(status);

create table if not exists public.passengers (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.travel_groups(id) on delete cascade,
  first_name text not null default '',
  last_name text not null default '',
  full_name text,
  passport_number text,
  passport_expiry date,
  date_of_birth date,
  nationality text,
  gender text,
  phone text,
  email text,
  room_number text,
  cabin_number text,
  emergency_contact text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_passengers_group on public.passengers(group_id);
create index if not exists idx_passengers_passport_expiry on public.passengers(passport_expiry);

create table if not exists public.passenger_import_logs (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.travel_groups(id) on delete cascade,
  file_name text not null default '',
  file_type text,
  row_count integer not null default 0,
  imported_count integer not null default 0,
  column_mapping jsonb,
  warnings jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_passenger_import_logs_group on public.passenger_import_logs(group_id);

alter table public.travel_groups enable row level security;
alter table public.passengers enable row level security;
alter table public.passenger_import_logs enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'travel_groups' and policyname = 'Authenticated can read travel_groups') then
    create policy "Authenticated can read travel_groups" on public.travel_groups for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'travel_groups' and policyname = 'Authenticated can insert travel_groups') then
    create policy "Authenticated can insert travel_groups" on public.travel_groups for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'travel_groups' and policyname = 'Authenticated can update travel_groups') then
    create policy "Authenticated can update travel_groups" on public.travel_groups for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'travel_groups' and policyname = 'Authenticated can delete travel_groups') then
    create policy "Authenticated can delete travel_groups" on public.travel_groups for delete to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'passengers' and policyname = 'Authenticated can read passengers') then
    create policy "Authenticated can read passengers" on public.passengers for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'passengers' and policyname = 'Authenticated can insert passengers') then
    create policy "Authenticated can insert passengers" on public.passengers for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'passengers' and policyname = 'Authenticated can update passengers') then
    create policy "Authenticated can update passengers" on public.passengers for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'passengers' and policyname = 'Authenticated can delete passengers') then
    create policy "Authenticated can delete passengers" on public.passengers for delete to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'passenger_import_logs' and policyname = 'Authenticated can read passenger_import_logs') then
    create policy "Authenticated can read passenger_import_logs" on public.passenger_import_logs for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'passenger_import_logs' and policyname = 'Authenticated can insert passenger_import_logs') then
    create policy "Authenticated can insert passenger_import_logs" on public.passenger_import_logs for insert to authenticated with check (true);
  end if;
end $$;

grant select, insert, update, delete on table public.travel_groups to authenticated;
grant select, insert, update, delete on table public.passengers to authenticated;
grant select, insert on table public.passenger_import_logs to authenticated;

notify pgrst, 'reload schema';
