-- Client accounts: debit/credit ledger, payments, invoice ↔ receipt linking

create table if not exists public.client_accounts (
  id bigint generated by default as identity primary key,
  client_id bigint not null unique references public.clients(id) on delete cascade,
  account_number text not null unique,
  currency text not null default 'EUR',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_client_accounts_client on public.client_accounts(client_id);
create index if not exists idx_client_accounts_number on public.client_accounts(account_number);

alter table public.client_financial_records
  add column if not exists account_id bigint references public.client_accounts(id) on delete set null;

alter table public.client_financial_records
  add column if not exists linked_invoice_id bigint references public.client_financial_records(id) on delete set null;

create table if not exists public.client_financial_payments (
  id bigint generated by default as identity primary key,
  financial_record_id bigint not null references public.client_financial_records(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  account_id bigint references public.client_accounts(id) on delete set null,
  amount numeric(12, 2) not null default 0 check (amount >= 0),
  payment_method text,
  payment_date date not null default current_date,
  receipt_no text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_client_fin_payments_record on public.client_financial_payments(financial_record_id);
create index if not exists idx_client_fin_payments_client on public.client_financial_payments(client_id);

create table if not exists public.client_ledger_entries (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  account_id bigint not null references public.client_accounts(id) on delete cascade,
  financial_record_id bigint references public.client_financial_records(id) on delete set null,
  payment_id bigint references public.client_financial_payments(id) on delete set null,
  entry_type text not null check (entry_type in ('debit', 'credit')),
  amount numeric(12, 2) not null default 0 check (amount >= 0),
  description text,
  reference_no text,
  entry_date date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists idx_client_ledger_client on public.client_ledger_entries(client_id);
create index if not exists idx_client_ledger_account on public.client_ledger_entries(account_id);
create index if not exists idx_client_ledger_date on public.client_ledger_entries(entry_date desc);

alter table public.client_accounts enable row level security;
alter table public.client_financial_payments enable row level security;
alter table public.client_ledger_entries enable row level security;

do $$
declare
  tbl text;
begin
  foreach tbl in array array['client_accounts', 'client_financial_payments', 'client_ledger_entries']
  loop
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = 'Authenticated can read ' || tbl
    ) then
      execute format(
        'create policy "Authenticated can read %I" on public.%I for select to authenticated using (true)',
        tbl, tbl
      );
    end if;
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = 'Authenticated can insert ' || tbl
    ) then
      execute format(
        'create policy "Authenticated can insert %I" on public.%I for insert to authenticated with check (true)',
        tbl, tbl
      );
    end if;
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = 'Authenticated can update ' || tbl
    ) then
      execute format(
        'create policy "Authenticated can update %I" on public.%I for update to authenticated using (true) with check (true)',
        tbl, tbl
      );
    end if;
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = 'Authenticated can delete ' || tbl
    ) then
      execute format(
        'create policy "Authenticated can delete %I" on public.%I for delete to authenticated using (true)',
        tbl, tbl
      );
    end if;
  end loop;
end $$;

grant select, insert, update, delete on table public.client_accounts to authenticated;
grant select, insert, update, delete on table public.client_financial_payments to authenticated;
grant select, insert, update, delete on table public.client_ledger_entries to authenticated;

notify pgrst, 'reload schema';
