-- Gift voucher module: receivers, vouchers, senders, payments, activity

create table if not exists public.voucher_receivers (
  id bigint generated by default as identity primary key,
  full_name text not null default '',
  phone text,
  email text,
  nationality text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gift_vouchers (
  id bigint generated by default as identity primary key,
  voucher_code text not null unique,
  voucher_title text not null default '',
  voucher_type text not null default 'custom'
    check (voucher_type in ('honeymoon', 'birthday', 'anniversary', 'holiday', 'travel_credit', 'custom')),
  receiver_id bigint references public.voucher_receivers(id) on delete set null,
  total_amount numeric(12, 2) not null default 0,
  currency text not null default 'EUR',
  status text not null default 'draft'
    check (status in ('draft', 'active', 'partially_paid', 'fully_paid', 'redeemed', 'expired', 'cancelled')),
  expiry_date date,
  gift_message text,
  template_key text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.voucher_senders (
  id bigint generated by default as identity primary key,
  voucher_id bigint not null references public.gift_vouchers(id) on delete cascade,
  full_name text not null default '',
  phone text,
  email text,
  contribution_amount numeric(12, 2) not null default 0,
  payment_status text not null default 'pending'
    check (payment_status in ('pending', 'paid', 'cancelled')),
  payment_method text
    check (payment_method is null or payment_method in ('cash', 'card', 'revolut', 'bank transfer', 'jcc', 'other')),
  payment_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.voucher_payments (
  id bigint generated by default as identity primary key,
  voucher_id bigint not null references public.gift_vouchers(id) on delete cascade,
  sender_id bigint references public.voucher_senders(id) on delete set null,
  amount numeric(12, 2) not null default 0,
  payment_method text,
  payment_status text not null default 'paid',
  payment_date timestamptz not null default now(),
  notes text,
  created_by_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.voucher_activities (
  id bigint generated by default as identity primary key,
  voucher_id bigint not null references public.gift_vouchers(id) on delete cascade,
  activity_type text not null default 'note',
  description text not null default '',
  metadata jsonb,
  created_by_name text,
  created_at timestamptz not null default now()
);

create index if not exists idx_gift_vouchers_code on public.gift_vouchers(lower(voucher_code));
create index if not exists idx_gift_vouchers_status on public.gift_vouchers(status);
create index if not exists idx_gift_vouchers_receiver on public.gift_vouchers(receiver_id);
create index if not exists idx_gift_vouchers_expiry on public.gift_vouchers(expiry_date);

create index if not exists idx_voucher_receivers_name on public.voucher_receivers(lower(full_name));
create index if not exists idx_voucher_receivers_phone on public.voucher_receivers(phone);
create index if not exists idx_voucher_receivers_email on public.voucher_receivers(lower(email));

create index if not exists idx_voucher_senders_voucher on public.voucher_senders(voucher_id);
create index if not exists idx_voucher_senders_name on public.voucher_senders(lower(full_name));
create index if not exists idx_voucher_senders_email on public.voucher_senders(lower(email));

create index if not exists idx_voucher_payments_voucher on public.voucher_payments(voucher_id);
create index if not exists idx_voucher_activities_voucher on public.voucher_activities(voucher_id);

alter table public.voucher_receivers enable row level security;
alter table public.gift_vouchers enable row level security;
alter table public.voucher_senders enable row level security;
alter table public.voucher_payments enable row level security;
alter table public.voucher_activities enable row level security;
