-- Client profiles table: public.clients
-- REST: /rest/v1/clients

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  first_name text not null default '',
  last_name text not null default '',
  email text,
  phone text,
  nationality text,
  date_of_birth date,
  passport_number text,
  date_of_issue date,
  date_of_expiry date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.leads
  add column if not exists client_id bigint references public.clients(id) on delete set null;

create index if not exists idx_clients_email on public.clients(lower(email));
create index if not exists idx_clients_passport_expiry on public.clients(date_of_expiry);
create index if not exists idx_leads_client_id on public.leads(client_id);

alter table public.clients enable row level security;
