-- Base leads table (run first on a new Supabase project).

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  full_name text,
  phone text,
  email text,
  destination text,
  travel_dates text,
  number_of_travelers text,
  budget text,
  message text,
  source text default 'Website',
  status text default 'New',
  notes text,
  follow_up_date date,
  assigned_agent text,
  deal_value numeric(12, 2) not null default 0,
  trip_type text,
  priority text default 'Normal',
  package_interest text,
  client_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists idx_leads_created_at on public.leads(created_at desc);
create index if not exists idx_leads_status on public.leads(status);
create index if not exists idx_leads_email on public.leads(lower(email));

alter table public.leads enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leads' and policyname = 'Authenticated can read leads'
  ) then
    create policy "Authenticated can read leads"
      on public.leads for select to authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leads' and policyname = 'Authenticated can insert leads'
  ) then
    create policy "Authenticated can insert leads"
      on public.leads for insert to authenticated with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leads' and policyname = 'Authenticated can update leads'
  ) then
    create policy "Authenticated can update leads"
      on public.leads for update to authenticated using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leads' and policyname = 'Authenticated can delete leads'
  ) then
    create policy "Authenticated can delete leads"
      on public.leads for delete to authenticated using (true);
  end if;
end $$;
