-- Corporate / group partners (B2B cooperations)

create table if not exists public.corporate_groups (
  id bigint generated by default as identity primary key,
  company_name text not null default '',
  industry text,
  status text not null default 'Active',
  contact_person text,
  contact_email text,
  contact_phone text,
  vat_number text,
  website text,
  address text,
  city text,
  country text default 'Cyprus',
  typical_group_size text,
  payment_terms text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_corporate_groups_company on public.corporate_groups(lower(company_name));
create index if not exists idx_corporate_groups_status on public.corporate_groups(status);

alter table public.corporate_groups enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'corporate_groups' and policyname = 'Authenticated can read corporate_groups'
  ) then
    create policy "Authenticated can read corporate_groups"
      on public.corporate_groups for select to authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'corporate_groups' and policyname = 'Authenticated can insert corporate_groups'
  ) then
    create policy "Authenticated can insert corporate_groups"
      on public.corporate_groups for insert to authenticated with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'corporate_groups' and policyname = 'Authenticated can update corporate_groups'
  ) then
    create policy "Authenticated can update corporate_groups"
      on public.corporate_groups for update to authenticated using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'corporate_groups' and policyname = 'Authenticated can delete corporate_groups'
  ) then
    create policy "Authenticated can delete corporate_groups"
      on public.corporate_groups for delete to authenticated using (true);
  end if;
end $$;

grant select, insert, update, delete on table public.corporate_groups to authenticated;
grant select on table public.corporate_groups to anon;

notify pgrst, 'reload schema';
