-- Honeywell CRM production upgrade
-- Adds revenue tracking, activity timeline, and baseline RLS.

alter table if exists public.leads
  add column if not exists deal_value numeric(12,2) not null default 0;

alter table if exists public.leads
  add column if not exists assigned_agent text;

create table if not exists public.lead_activities (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  type text not null,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by uuid
);

create index if not exists idx_leads_created_at on public.leads(created_at desc);
create index if not exists idx_leads_status on public.leads(status);
create index if not exists idx_leads_follow_up_date on public.leads(follow_up_date);
create index if not exists idx_leads_assigned_agent on public.leads(assigned_agent);
create index if not exists idx_leads_destination on public.leads(destination);
create index if not exists idx_activities_lead_id_created_at on public.lead_activities(lead_id, created_at desc);

alter table public.leads enable row level security;
alter table public.lead_activities enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leads' and policyname = 'Authenticated can read leads'
  ) then
    create policy "Authenticated can read leads"
      on public.leads
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leads' and policyname = 'Authenticated can insert leads'
  ) then
    create policy "Authenticated can insert leads"
      on public.leads
      for insert
      to authenticated
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leads' and policyname = 'Authenticated can update leads'
  ) then
    create policy "Authenticated can update leads"
      on public.leads
      for update
      to authenticated
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leads' and policyname = 'Authenticated can delete leads'
  ) then
    create policy "Authenticated can delete leads"
      on public.leads
      for delete
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'lead_activities' and policyname = 'Authenticated can read lead activities'
  ) then
    create policy "Authenticated can read lead activities"
      on public.lead_activities
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'lead_activities' and policyname = 'Authenticated can insert lead activities'
  ) then
    create policy "Authenticated can insert lead activities"
      on public.lead_activities
      for insert
      to authenticated
      with check (true);
  end if;
end $$;
