-- Ensure public.clients has all CRM columns (table: clients only, no spaces).
-- REST: https://vrrjljdvtzvfcottdvns.supabase.co/rest/v1/clients

alter table if exists public.clients
  add column if not exists id bigint generated by default as identity;

alter table if exists public.clients
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists nationality text,
  add column if not exists date_of_birth date,
  add column if not exists passport_number text,
  add column if not exists date_of_issue date,
  add column if not exists date_of_expiry date,
  add column if not exists notes text;

alter table if exists public.leads
  add column if not exists client_id bigint references public.clients(id) on delete set null;

create index if not exists idx_leads_client_id on public.leads(client_id);
create index if not exists idx_clients_email on public.clients(lower(email));
create index if not exists idx_clients_passport_expiry on public.clients(date_of_expiry);

alter table public.clients enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'clients' and policyname = 'Authenticated can read clients'
  ) then
    create policy "Authenticated can read clients"
      on public.clients for select to authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'clients' and policyname = 'Authenticated can insert clients'
  ) then
    create policy "Authenticated can insert clients"
      on public.clients for insert to authenticated with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'clients' and policyname = 'Authenticated can update clients'
  ) then
    create policy "Authenticated can update clients"
      on public.clients for update to authenticated using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'clients' and policyname = 'Authenticated can delete clients'
  ) then
    create policy "Authenticated can delete clients"
      on public.clients for delete to authenticated using (true);
  end if;
end $$;
