-- Per-service category contact details for the Services Hub.

create table if not exists public.corporate_service_profiles (
  id bigint generated by default as identity primary key,
  category text not null unique,
  company_name text,
  contact_name text,
  email text,
  phone text,
  country text default 'Cyprus',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_corp_svc_profiles_category on public.corporate_service_profiles(category);

alter table public.corporate_service_profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'corporate_service_profiles'
      and policyname = 'Authenticated can read corporate_service_profiles'
  ) then
    create policy "Authenticated can read corporate_service_profiles"
      on public.corporate_service_profiles for select to authenticated using (true);
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'corporate_service_profiles'
      and policyname = 'Authenticated can insert corporate_service_profiles'
  ) then
    create policy "Authenticated can insert corporate_service_profiles"
      on public.corporate_service_profiles for insert to authenticated with check (true);
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'corporate_service_profiles'
      and policyname = 'Authenticated can update corporate_service_profiles'
  ) then
    create policy "Authenticated can update corporate_service_profiles"
      on public.corporate_service_profiles for update to authenticated using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'corporate_service_profiles'
      and policyname = 'Authenticated can delete corporate_service_profiles'
  ) then
    create policy "Authenticated can delete corporate_service_profiles"
      on public.corporate_service_profiles for delete to authenticated using (true);
  end if;
end $$;

grant select, insert, update, delete on table public.corporate_service_profiles to authenticated;
